Milestone4/logic
epinczinger/calculator pull request #3
Opened 2021-03-25 16:24 UTC by epinczinger

On this branch, I've worked on the following specifics:

- Create App Logics.
- Add Operate component.
- Add Calculate component.
- Style of the app, implemented with Tailwind, following a responsive design.
- Eslint errors have been fixed.

2021-03-25 20:42 UTC, wathigo requested changes
## CHANGES REQUIRED :o: 
Great job on this milestone.
Let's fix one issue before we move on. See the comment :point_down: 

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2021-03-25 20:42 UTC, wathigo commented on src/components/App.js
>  export default function App() {
**REQUIRED** 
* calculate.js is imported in the App component.
![Screenshot from 2021-03-25 16-36-18](https://user-images.githubusercontent.com/44072711/112540602-c1b70d80-8d88-11eb-8cf0-98ee8e06e72f.png)

2021-03-26 00:47 UTC, epinczinger commented
Calculate is being imported on App but is commented on in order to avoid Eslint errors.

2021-03-26 01:18 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @epinczinger, congratulations on this project :fireworks: Having imported the calculate.js file in the app component as outlined in the previous review :muscle: I hereby approve the project :+1: 

Kindly go ahead and merge into development :+1: Do not forget to submit the project completion form
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-03-26 01:22 UTC, merged